// Code generated by MockGen. DO NOT EDIT.
// Source: jira.go
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=readonly -source jira.go -destination ./mock/jiramock.go -package jiramock
//

// Package jiramock is a generated GoMock package.
package jiramock

import (
	context "context"
	reflect "reflect"

	jira "github.com/openshift/configuration-anomaly-detection/pkg/jira"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetOpenOHSSTickets mocks base method.
func (m *MockClient) GetOpenOHSSTickets(ctx context.Context, clusterID, externalID string) ([]jira.OHSSTicket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenOHSSTickets", ctx, clusterID, externalID)
	ret0, _ := ret[0].([]jira.OHSSTicket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenOHSSTickets indicates an expected call of GetOpenOHSSTickets.
func (mr *MockClientMockRecorder) GetOpenOHSSTickets(ctx, clusterID, externalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenOHSSTickets", reflect.TypeOf((*MockClient)(nil).GetOpenOHSSTickets), ctx, clusterID, externalID)
}
